### ISSUE TITLE
Database box in Advanced

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#1]
- https://cgzqrodssn.d.braathedev.no/app/site/si0l0mx5i
- in Advanced tab
- can you make sure we only display the whole Database box if
- appservices.db_name != ''
- No reason to display it if the service have no db
- the name in that box is also wrong:
- Database Name have to come from
- appservices.db_name column in the database

**Comment by jazzyuser** [comment]
Added
