### ISSUE TITLE
add wp admin login link

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#14]
### Add WP Admin to the list of dropdown

- On wp/site page, under action dropdown in the navigation tool. Add "WP Admin" to list and redirect URL to wp-login.php

![BE53EAAD-38EF-400E-90D6-5A522E8434A8](https://user-images.githubusercontent.com/61142241/76474303-292c4480-6436-11ea-81a9-c83da65e6980.png)

**Comment by tagslyf** [comment]
PR: #17

**Comment by AppBasky** [comment]
https://3bvu3d4dtz.d.braathedev.no/wp-login.php
the link should be the domain+wp-login

**Comment by tagslyf** [comment]
Added wp-login redirect in action tab.

**Comment by tagslyf** [comment]
PR updated
