### ISSUE TITLE
fix responsive issue of dashboard

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#19]
### Fix responsive issue

- remove coreui logo broken link
![4383E25E-CFA0-4642-BBC1-64BD82C3C0D3](https://user-images.githubusercontent.com/61142241/76598181-4a2b8d00-653d-11ea-8992-d76ceb75cdef.png)
- Fix responsive issue of the simple dashboard

check other window size on chrome window resizer

**Comment by jazzyuser** [comment]
Fixed - https://github.com/AppBasky/ABWeb/pull/20
