### ISSUE TITLE
Totally change Config Variables in advanced

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#2]
- Config Variables in advanced
- please remove all code for this as its never worked and do not follow any of our existing designs
- every variable will be displayed in a very simple 2 colum html list. 
- we will have a simple Edit link similar to the image below from P2
- We will have a simple Add Config Variable button similar to what we have in Add collaborator
- This is our way of making UX elements.
- It is really important we do not invent a new UX everytime we have a new feature. How can users low our application when every part of it works in a different way

![image](https://user-images.githubusercontent.com/61142241/75852661-cb23af80-5dec-11ea-8415-8d6d2d111274.png)

![image](https://user-images.githubusercontent.com/61142241/75852852-38374500-5ded-11ea-94f5-9c93136d6be1.png)

**Comment by jazzyuser** [comment]
Added
