### ISSUE TITLE
413 Request entity too large

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#22]
### Won't allow me to upload a theme of 9.2mb

https://www.cloudways.com/blog/increase-media-file-maximum-upload-size-in-wordpress/

![Screen Shot 2020-03-26 at 2 10 41 PM](https://user-images.githubusercontent.com/61142241/77616284-3f74ed00-6f6c-11ea-9c0f-78e4c7bde2a2.png)

**Comment by koneb71** [comment]
done @AppBasky
