### ISSUE TITLE
Add link to a page from Correlation ID

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#24]
### Add a link to a page from Correlation ID

![A543DA00-DD39-41E2-B7DA-08F116FAF431](https://user-images.githubusercontent.com/61142241/77730572-01df9500-703c-11ea-8fdd-fc524a235b7f.png)

Display the resource (Pipeline configuration)
![Screen Shot 2020-03-27 at 2 57 48 PM](https://user-images.githubusercontent.com/61142241/77730687-3eab8c00-703c-11ea-9869-4a3f1dfd37a1.png)
![Screen Shot 2020-03-27 at 2 58 04 PM](https://user-images.githubusercontent.com/61142241/77730697-423f1300-703c-11ea-8bb0-01a595840ad4.png)

**Comment by tagslyf** [comment]
https://github.com/AppBasky/ABWeb/pull/29

**Comment by tagslyf** [comment]
![Screen Shot 2020-03-31 at 14 55 57](https://user-images.githubusercontent.com/13956974/77996553-64989f80-7360-11ea-96fb-75107ca2fca7.png)
![Screen Shot 2020-03-31 at 14 54 51](https://user-images.githubusercontent.com/13956974/77996562-682c2680-7360-11ea-89ad-db34662ea1d9.png)
![Screen Shot 2020-03-31 at 14 54 07](https://user-images.githubusercontent.com/13956974/77996564-68c4bd00-7360-11ea-9e7a-2a5b49ff98ac.png)
![Screen Shot 2020-03-31 at 14 53 52](https://user-images.githubusercontent.com/13956974/77996565-69f5ea00-7360-11ea-8f73-ba75a749e060.png)
![Screen Shot 2020-03-31 at 14 53 44](https://user-images.githubusercontent.com/13956974/77996567-6a8e8080-7360-11ea-9616-dcf17eb81010.png)
