### ISSUE TITLE
AppBasky Teams

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#27]
- Please make Neiell and me Owners of our team. So @koneb71 can do his task #28 

![image](https://user-images.githubusercontent.com/61142241/77840648-ef737180-7189-11ea-9d74-bac3eaa99a18.png)

**Comment by jeyzey** [comment]
![Screen Shot 2020-03-30 at 8 32 12 AM](https://user-images.githubusercontent.com/12162681/77865543-73e4f380-7261-11ea-9987-59ac97ab15e9.png)

Added Neiell as Owner
