### ISSUE TITLE
WP Quality Control

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#34]
- We need to analyse our Nginx config
- https://github.com/yandex/gixy 
- Use Gixy tool to analyze Nginx configuration to prevent security misconfiguration
- https://developers.google.com/speed/pagespeed/insights/
- We have to be sure that all the static files are servied by nginx only. Not by php frm. This affect the speed.
- We have to be sure all static objects  have nginx caching parameters
- We also need to be sure our site passes this tests
    - https://observatory.mozilla.org/
    - https://www.ssllabs.com/ssltest/

**Comment by koneb71** [comment]
Update:
Pagespeed Score : 95%
Observatory score: 80/100
Gixy: No issue
