### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by jeyzey** [AppBasky/ABWeb#35]
Internal server error when creating new wordpress site.
![Screen Shot 2020-04-02 at 2 27 56 PM](https://user-images.githubusercontent.com/12162681/78217247-41035f80-74ee-11ea-914c-9945591af691.png)

Deploying 3 Wordpress site
![DDF359E3-7E34-4B76-BF66-ABDE1E54404A](https://user-images.githubusercontent.com/12162681/78217450-b4a56c80-74ee-11ea-9e93-265e0a3c31e4.png)

**Comment by koneb71** [comment]
fixed
