### ISSUE TITLE
Make the event filter as a search bar

### ISSUE THREAD

**Issue by jeyzey** [AppBasky/ABWeb#37]
Make the event filter as a search bar
![5DCC5E45-4EEB-45F9-A0DE-776FDE23CAA8](https://user-images.githubusercontent.com/12162681/78218731-d9024880-74f0-11ea-8f0c-ef4b472bba07.png)

Replace it as general search bar.

**Comment by tagslyf** [comment]
PR: https://github.com/AppBasky/ABWeb/pull/41
