### ISSUE TITLE
Add display filter to the events page

### ISSUE THREAD

**Issue by jeyzey** [AppBasky/ABWeb#38]
Add display filter to the events page

![73A98F51-85E6-4B5F-B187-1605495DC274](https://user-images.githubusercontent.com/12162681/78219048-6180e900-74f1-11ea-934f-cba3424b0f59.png)
![EEF1CBAC-CA36-4DAD-9588-6A40DB1336DD](https://user-images.githubusercontent.com/12162681/78219073-6c3b7e00-74f1-11ea-9536-fd7a6fba49ce.png)

**Comment by tagslyf** [comment]
PR: https://github.com/AppBasky/ABWeb/pull/41
