### ISSUE TITLE
list the newly created wordpress site

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#5]
### List the newly created wordpress site

- https://applab.braathedev.no/wp/create
- create new event

wordpress created list to https://applab.braathedev.no/wp/list

![1C078E24-0ACB-4368-AFBB-5E808E2A7E8B](https://user-images.githubusercontent.com/61142241/76191338-2228ea80-621a-11ea-8063-bf3518f7f2b7.png)

**Comment by tagslyf** [comment]
https://github.com/AppBasky/ABWeb/pull/11

**Comment by AppBasky** [comment]
https://3bvu3d4dtz.d.braathedev.no/wp/create
- temporary domain (should display the .domain info below)
- add placeholder (put text in the placeholder)
