### ISSUE TITLE
copy same ui of appserver list

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#6]
### Copy the UI of appserver/list to wp/list

![B547E39E-D9F2-43A4-8C2C-98E305CF93B0](https://user-images.githubusercontent.com/61142241/76191549-906dad00-621a-11ea-8d27-6bdc13264596.png)
https://applab.braathedev.no/appserver/list

> Header text: Welcome to AppBasky
We think you're really going to like our easy to use managed Wordpress site hosting 

- thumbnail
- wordpress site name
- wordpress site domain
- display filter
- search filter
- New Wordpress Site button
- collaborator
- add contractor

https://applab.braathedev.no/wp/list
![F51916F7-5DD3-4B2A-9E05-ED3D822EE25E](https://user-images.githubusercontent.com/61142241/76191812-2bff1d80-621b-11ea-99eb-5bbeba19d126.png)

**Comment by tagslyf** [comment]
https://github.com/AppBasky/ABWeb/pull/11
