### ISSUE TITLE
Make linkable url from every tab

### ISSUE THREAD

**Issue by astbss** [AppBasky/ABWeb#7]
- Clone: master and make Pull request
- This is implemented in P2 Users. So you do a the same so we use same url format
- Look at this url in P2
- http://localhost:5000/adusers/ZXZ?activetab=preprod#change-log-tab
- You cans see that every tab have a name and we can link to the tab directly like the link above.
- Implement this for the tabs we have in AppBasky so we can link to every tab using url
- Change the save form in Config / Enviroment so it returns direct to the correct Advanced tab.

**Comment by jazzyuser** [comment]
Added - https://github.com/AppBasky/ABWeb/pull/15
