### ISSUE TITLE
Wordpress site info

### ISSUE THREAD

**Issue by AppBasky** [AppBasky/ABWeb#8]
### Make Wordpress site info page
Copy -> https://applab.braathedev.no/app/site

![BC45FC02-2A85-450B-BF48-3B2EFCF178C2](https://user-images.githubusercontent.com/61142241/76193069-2e16ab80-621e-11ea-9717-cfb3dddbc2bf.png)

https://applab.braathedev.no/wp/site/
- Add Overview Tab
- Add Backups tab
- Add Advanced tab
![CF8A6039-4671-45F5-8C92-598BEB29075D](https://user-images.githubusercontent.com/61142241/76193224-7f269f80-621e-11ea-8c49-b76744a7082c.png)
- Add Recent Changes

**Comment by tagslyf** [comment]
PR: https://github.com/AppBasky/ABWeb/pull/17

**Comment by tagslyf** [comment]
PR updated.

1. Added instance_name and service_name (8 random string)
2. Use `deployment_wordpress.j2` for `jinja2_template` field
3. Set `service_port` to `80`
4. Generate random db_name, db_username and db_password. ("tmp" + 6 random string)
